//*
// Standalone signaling server for the Nextcloud Spreed app.
// Copyright (C) 2022 struktur AG
//
// @author Joachim Bauch <bauch@struktur.de>
//
// @license GNU AGPL version 3 or any later version
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/backend.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSessionCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionCountRequest) Reset() {
	*x = GetSessionCountRequest{}
	mi := &file_grpc_backend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionCountRequest) ProtoMessage() {}

func (x *GetSessionCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_backend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionCountRequest.ProtoReflect.Descriptor instead.
func (*GetSessionCountRequest) Descriptor() ([]byte, []int) {
	return file_grpc_backend_proto_rawDescGZIP(), []int{0}
}

func (x *GetSessionCountRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetSessionCountReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint32                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionCountReply) Reset() {
	*x = GetSessionCountReply{}
	mi := &file_grpc_backend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionCountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionCountReply) ProtoMessage() {}

func (x *GetSessionCountReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_backend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionCountReply.ProtoReflect.Descriptor instead.
func (*GetSessionCountReply) Descriptor() ([]byte, []int) {
	return file_grpc_backend_proto_rawDescGZIP(), []int{1}
}

func (x *GetSessionCountReply) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_grpc_backend_proto protoreflect.FileDescriptor

const file_grpc_backend_proto_rawDesc = "" +
	"\n" +
	"\x12grpc/backend.proto\x12\x04grpc\"*\n" +
	"\x16GetSessionCountRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\",\n" +
	"\x14GetSessionCountReply\x12\x14\n" +
	"\x05count\x18\x01 \x01(\rR\x05count2[\n" +
	"\n" +
	"RpcBackend\x12M\n" +
	"\x0fGetSessionCount\x12\x1c.grpc.GetSessionCountRequest\x1a\x1a.grpc.GetSessionCountReply\"\x00B7Z5github.com/strukturag/nextcloud-spreed-signaling/grpcb\x06proto3"

var (
	file_grpc_backend_proto_rawDescOnce sync.Once
	file_grpc_backend_proto_rawDescData []byte
)

func file_grpc_backend_proto_rawDescGZIP() []byte {
	file_grpc_backend_proto_rawDescOnce.Do(func() {
		file_grpc_backend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_backend_proto_rawDesc), len(file_grpc_backend_proto_rawDesc)))
	})
	return file_grpc_backend_proto_rawDescData
}

var file_grpc_backend_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_backend_proto_goTypes = []any{
	(*GetSessionCountRequest)(nil), // 0: grpc.GetSessionCountRequest
	(*GetSessionCountReply)(nil),   // 1: grpc.GetSessionCountReply
}
var file_grpc_backend_proto_depIdxs = []int32{
	0, // 0: grpc.RpcBackend.GetSessionCount:input_type -> grpc.GetSessionCountRequest
	1, // 1: grpc.RpcBackend.GetSessionCount:output_type -> grpc.GetSessionCountReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_backend_proto_init() }
func file_grpc_backend_proto_init() {
	if File_grpc_backend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_backend_proto_rawDesc), len(file_grpc_backend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_backend_proto_goTypes,
		DependencyIndexes: file_grpc_backend_proto_depIdxs,
		MessageInfos:      file_grpc_backend_proto_msgTypes,
	}.Build()
	File_grpc_backend_proto = out.File
	file_grpc_backend_proto_goTypes = nil
	file_grpc_backend_proto_depIdxs = nil
}
