//*
// Standalone signaling server for the Nextcloud Spreed app.
// Copyright (C) 2022 struktur AG
//
// @author Joachim Bauch <bauch@struktur.de>
//
// @license GNU AGPL version 3 or any later version
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/internal.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetServerIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerIdRequest) Reset() {
	*x = GetServerIdRequest{}
	mi := &file_grpc_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerIdRequest) ProtoMessage() {}

func (x *GetServerIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerIdRequest.ProtoReflect.Descriptor instead.
func (*GetServerIdRequest) Descriptor() ([]byte, []int) {
	return file_grpc_internal_proto_rawDescGZIP(), []int{0}
}

type GetServerIdReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=serverId,proto3" json:"serverId,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerIdReply) Reset() {
	*x = GetServerIdReply{}
	mi := &file_grpc_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerIdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerIdReply) ProtoMessage() {}

func (x *GetServerIdReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerIdReply.ProtoReflect.Descriptor instead.
func (*GetServerIdReply) Descriptor() ([]byte, []int) {
	return file_grpc_internal_proto_rawDescGZIP(), []int{1}
}

func (x *GetServerIdReply) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *GetServerIdReply) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetTransientDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	BackendUrls   []string               `protobuf:"bytes,2,rep,name=backendUrls,proto3" json:"backendUrls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransientDataRequest) Reset() {
	*x = GetTransientDataRequest{}
	mi := &file_grpc_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransientDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransientDataRequest) ProtoMessage() {}

func (x *GetTransientDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransientDataRequest.ProtoReflect.Descriptor instead.
func (*GetTransientDataRequest) Descriptor() ([]byte, []int) {
	return file_grpc_internal_proto_rawDescGZIP(), []int{2}
}

func (x *GetTransientDataRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GetTransientDataRequest) GetBackendUrls() []string {
	if x != nil {
		return x.BackendUrls
	}
	return nil
}

type GrpcTransientDataEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Expires       int64                  `protobuf:"varint,2,opt,name=expires,proto3" json:"expires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcTransientDataEntry) Reset() {
	*x = GrpcTransientDataEntry{}
	mi := &file_grpc_internal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcTransientDataEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcTransientDataEntry) ProtoMessage() {}

func (x *GrpcTransientDataEntry) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcTransientDataEntry.ProtoReflect.Descriptor instead.
func (*GrpcTransientDataEntry) Descriptor() ([]byte, []int) {
	return file_grpc_internal_proto_rawDescGZIP(), []int{3}
}

func (x *GrpcTransientDataEntry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GrpcTransientDataEntry) GetExpires() int64 {
	if x != nil {
		return x.Expires
	}
	return 0
}

type GetTransientDataReply struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Entries       map[string]*GrpcTransientDataEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransientDataReply) Reset() {
	*x = GetTransientDataReply{}
	mi := &file_grpc_internal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransientDataReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransientDataReply) ProtoMessage() {}

func (x *GetTransientDataReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransientDataReply.ProtoReflect.Descriptor instead.
func (*GetTransientDataReply) Descriptor() ([]byte, []int) {
	return file_grpc_internal_proto_rawDescGZIP(), []int{4}
}

func (x *GetTransientDataReply) GetEntries() map[string]*GrpcTransientDataEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_grpc_internal_proto protoreflect.FileDescriptor

const file_grpc_internal_proto_rawDesc = "" +
	"\n" +
	"\x13grpc/internal.proto\x12\x04grpc\"\x14\n" +
	"\x12GetServerIdRequest\"H\n" +
	"\x10GetServerIdReply\x12\x1a\n" +
	"\bserverId\x18\x01 \x01(\tR\bserverId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"S\n" +
	"\x17GetTransientDataRequest\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\x12 \n" +
	"\vbackendUrls\x18\x02 \x03(\tR\vbackendUrls\"H\n" +
	"\x16GrpcTransientDataEntry\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x18\n" +
	"\aexpires\x18\x02 \x01(\x03R\aexpires\"\xb5\x01\n" +
	"\x15GetTransientDataReply\x12B\n" +
	"\aentries\x18\x01 \x03(\v2(.grpc.GetTransientDataReply.EntriesEntryR\aentries\x1aX\n" +
	"\fEntriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.grpc.GrpcTransientDataEntryR\x05value:\x028\x012\xa2\x01\n" +
	"\vRpcInternal\x12A\n" +
	"\vGetServerId\x12\x18.grpc.GetServerIdRequest\x1a\x16.grpc.GetServerIdReply\"\x00\x12P\n" +
	"\x10GetTransientData\x12\x1d.grpc.GetTransientDataRequest\x1a\x1b.grpc.GetTransientDataReply\"\x00B7Z5github.com/strukturag/nextcloud-spreed-signaling/grpcb\x06proto3"

var (
	file_grpc_internal_proto_rawDescOnce sync.Once
	file_grpc_internal_proto_rawDescData []byte
)

func file_grpc_internal_proto_rawDescGZIP() []byte {
	file_grpc_internal_proto_rawDescOnce.Do(func() {
		file_grpc_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_internal_proto_rawDesc), len(file_grpc_internal_proto_rawDesc)))
	})
	return file_grpc_internal_proto_rawDescData
}

var file_grpc_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_grpc_internal_proto_goTypes = []any{
	(*GetServerIdRequest)(nil),      // 0: grpc.GetServerIdRequest
	(*GetServerIdReply)(nil),        // 1: grpc.GetServerIdReply
	(*GetTransientDataRequest)(nil), // 2: grpc.GetTransientDataRequest
	(*GrpcTransientDataEntry)(nil),  // 3: grpc.GrpcTransientDataEntry
	(*GetTransientDataReply)(nil),   // 4: grpc.GetTransientDataReply
	nil,                             // 5: grpc.GetTransientDataReply.EntriesEntry
}
var file_grpc_internal_proto_depIdxs = []int32{
	5, // 0: grpc.GetTransientDataReply.entries:type_name -> grpc.GetTransientDataReply.EntriesEntry
	3, // 1: grpc.GetTransientDataReply.EntriesEntry.value:type_name -> grpc.GrpcTransientDataEntry
	0, // 2: grpc.RpcInternal.GetServerId:input_type -> grpc.GetServerIdRequest
	2, // 3: grpc.RpcInternal.GetTransientData:input_type -> grpc.GetTransientDataRequest
	1, // 4: grpc.RpcInternal.GetServerId:output_type -> grpc.GetServerIdReply
	4, // 5: grpc.RpcInternal.GetTransientData:output_type -> grpc.GetTransientDataReply
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_grpc_internal_proto_init() }
func file_grpc_internal_proto_init() {
	if File_grpc_internal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_internal_proto_rawDesc), len(file_grpc_internal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_internal_proto_goTypes,
		DependencyIndexes: file_grpc_internal_proto_depIdxs,
		MessageInfos:      file_grpc_internal_proto_msgTypes,
	}.Build()
	File_grpc_internal_proto = out.File
	file_grpc_internal_proto_goTypes = nil
	file_grpc_internal_proto_depIdxs = nil
}
